<?php

namespace Database\Seeders;

use App\Models\Participant;
use Illuminate\Database\Seeder;

class ParticipantJsonSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['nom' => 'KABO', 'prenom' => 'Kossi', 'email' => 'fofokabo@gmail.com'],
            ['nom' => 'BENSMAA', 'prenom' => 'Soukaina', 'email' => 'soukaina.bensmaa@edu.uiz.ac.ma'],
            ['nom' => 'Lahnini', 'prenom' => 'Rihab', 'email' => 'Rihabhn2208@gmail.com'],
            ['nom' => 'YOUB', 'prenom' => 'MOHAMEDAMINE', 'email' => 'm.youb@uhp.ac.ma'],
            ['nom' => 'BOULLA', 'prenom' => 'DOUHA', 'email' => 'douhaboulla@gmail.com'],
            ['nom' => 'EL HANDOUR', 'prenom' => 'Farah', 'email' => 'farahelhandour@gmail.com'],
            ['nom' => 'Tayari', 'prenom' => 'Oumaima', 'email' => 'tayoumaima@gmail.com'],
            ['nom' => 'tamri', 'prenom' => 'otman', 'email' => 'otman.tamri5@gmail.com'],
            ['nom' => 'JMAILI', 'prenom' => 'Karima', 'email' => 'karimajmaili33@gmail.com'],
            ['nom' => 'NDIKUMANA', 'prenom' => 'SYLVERE', 'email' => 'sylvere.ndikumana-etu@etu.univh2c.ma'],
            ['nom' => 'EL MOUNS', 'prenom' => 'Karim', 'email' => 'elmouns.karim@ucd.ac.ma'],
            ['nom' => 'Mahmoudi', 'prenom' => 'Meriem', 'email' => 'meriem.mahmoudi2-etu@etu.univh2c.ma'],
            ['nom' => 'BEN KACEM ZIANI', 'prenom' => 'HASNAE', 'email' => 'hasnaebenkacemziani@gmail.com'],
            ['nom' => 'IYOUBI', 'prenom' => 'EL MEHDI', 'email' => 'elmehdiiyoubi99@gmail.com'],
            ['nom' => 'RAZAFINDRASAMY', 'prenom' => 'Rosa Nobella', 'email' => 'razafindrasamyrosa@gmail.com'],
            ['nom' => 'Belhimer', 'prenom' => 'Miloud', 'email' => 'belhimer.miloud@gmail.com'],
            ['nom' => 'El Hafiane', 'prenom' => 'Fouzia', 'email' => 'fouzia.elhafiane@usms.ma'],
            ['nom' => 'barouaca', 'prenom' => 'hassan', 'email' => 'barouaca@yahoo.fr'],
            ['nom' => 'Wann', 'prenom' => 'Amadou', 'email' => 'amadouwann38@gmail.com'],
            ['nom' => 'KONATE', 'prenom' => 'Fousseyni', 'email' => 'fousseyni.konate95@gmail.com'],
            ['nom' => 'ANIBA', 'prenom' => 'RAFIK', 'email' => 'RAFIKANIBA1466@gmail.com'],
            ['nom' => 'Maiouet', 'prenom' => 'Imane', 'email' => 'imanemaiouet@gmail.com'],
            ['nom' => 'KASSBi', 'prenom' => 'Ayman', 'email' => 'Kassbiayman@gmail.com'],
            ['nom' => 'FARIAT', 'prenom' => 'YOUSRA', 'email' => 'yousrafariat1999@gmail.com'],
            ['nom' => 'ABBAS', 'prenom' => 'Lahbib', 'email' => 'l.abbas@umi.ac.ma'],
            ['nom' => 'AZOUGAGH', 'prenom' => 'WIAME', 'email' => 'wiame.azougagh@gmail.com'],
            ['nom' => 'El Agy', 'prenom' => 'Fatima', 'email' => 'fatima.elagy@usmba.ac.ma'],
            ['nom' => 'Aalilouch', 'prenom' => 'Kaoutar', 'email' => 'Kaoutar.lst.ba@gmail.com'],
            ['nom' => 'ABBADI', 'prenom' => 'ABDELHADI', 'email' => 'abbadi.abdelhadi@gmail.com'],
            ['nom' => 'OUMALK', 'prenom' => 'KAWTAR', 'email' => 'kawtar.oumalk@uit.ac.ma'],
            ['nom' => 'Mouslih', 'prenom' => 'Assia', 'email' => 'assia.mouslih@usmba.ac.ma'],
            ['nom' => 'ELBIRGUI', 'prenom' => 'Kaouthar', 'email' => 'kaouthar.elbirgui-etu@etu.univh2c.ma'],
            ['nom' => 'MINOUAL', 'prenom' => 'SARA', 'email' => 'minoualsara@gmail.com'],
            ['nom' => 'Lasri', 'prenom' => 'Siham', 'email' => 'siham.lasri23@gmail.com'],
            ['nom' => 'AMRANE', 'prenom' => 'younesse', 'email' => 'Amrane1youness2@gmail.com'],
            ['nom' => 'TESSE', 'prenom' => 'Rajaa', 'email' => 'rajaatesse@gmail.com'],
            ['nom' => 'ZAINELABIDINE', 'prenom' => 'Hind', 'email' => 'hind.zainelabidine-etu@etu.univh2c.ma'],
            ['nom' => 'OUAHMANE', 'prenom' => 'LOUBNA', 'email' => 'Loubna.ouahmane.62@edu.uiz.ac.ma'],
            ['nom' => 'EL MARJANY', 'prenom' => 'SOFIA', 'email' => 'sofia.elmarjany@usmba.ac.ma'],
            ['nom' => 'elbezyouy', 'prenom' => 'ikram', 'email' => 'ikramelbezyouy@gmail.com'],
            ['nom' => 'EL MALAHI', 'prenom' => 'Soumia', 'email' => 'soumia.elmalahi98@gmail.com'],
            ['nom' => 'BEN ELHADJ ALI', 'prenom' => 'Imen', 'email' => 'imen.202@gmail.com'],
            ['nom' => 'BOUZAR', 'prenom' => 'ZAKARIA', 'email' => 'zakariabouzar201@gmail.com'],
            ['nom' => 'FAYED', 'prenom' => 'Wiam', 'email' => 'fayedwiam167@gmail.com'],
            ['nom' => 'Bouchra', 'prenom' => 'Oumaima', 'email' => 'oumaimabouchra@gmail.com'],
            ['nom' => 'Ganoudi', 'prenom' => 'Matike', 'email' => 'ganoudi@gmail.com'],
            ['nom' => 'ALQASSASS', 'prenom' => 'Haroun', 'email' => 'Harounalqassass@gmail.com'],
            ['nom' => 'NADI', 'prenom' => 'HAMID', 'email' => 'nadihami01@gmail.com'],
            ['nom' => 'HARKAT', 'prenom' => 'Chaymaa', 'email' => 'c.harkat.ced@uca.ac.ma'],
            ['nom' => 'ESSALIHI', 'prenom' => 'Amina', 'email' => 'aminaessalihi155@gmail.com'],
            ['nom' => 'LATRACHE', 'prenom' => 'loubna', 'email' => 'loubnalatrache6@gmail.com'],
            ['nom' => 'Alami', 'prenom' => 'Oumaima', 'email' => 'oumaima.alami.pro@gmail.com'],
            ['nom' => 'ESSOUBAIY', 'prenom' => 'Othmane', 'email' => 'othmane.essoub@gmail.com'],
            ['nom' => 'EL HJOUJI', 'prenom' => 'WIAME', 'email' => 'WIAMEELHJOUJI@GMAIL.COM'],
            ['nom' => 'Lakrimi', 'prenom' => 'Khaoula', 'email' => 'khaoula.lakrimi@etu.uae.ac.ma'],
            ['nom' => 'bouchama', 'prenom' => 'abdelfattah', 'email' => 'abdelfattah.bouchama@uit.ac.ma'],
            ['nom' => 'Aicha', 'prenom' => 'Boubker', 'email' => 'aicha.boubker@um5r.ac.ma'],
            ['nom' => 'TALI', 'prenom' => 'Assmaa', 'email' => 'assmaa.tali@usms.ac.ma'],
            ['nom' => 'LOURHLAM', 'prenom' => 'Bouchra', 'email' => 'bouchra.lourhlam@usms.ma'],
            ['nom' => 'Samaila Zakari', 'prenom' => 'Assoumana', 'email' => 'assoumana209@gmail.com'],
            ['nom' => 'Mahamed', 'prenom' => 'Oumar Abakar', 'email' => 'mahamedoumara@gmail.com'],
            ['nom' => 'Bouhdadi', 'prenom' => 'Ayoub', 'email' => 'ayoubbouhdadi19@gmail.com'],
            ['nom' => 'DOLOU', 'prenom' => 'Malibida', 'email' => 'dmalibida@gmail.com'],
            ['nom' => 'NTIHEBUWAYO', 'prenom' => 'Zacharie', 'email' => 'zacharientihebuwayo36@gmail.com'],
            ['nom' => 'HAGGAR', 'prenom' => 'Abakar', 'email' => 'abakar.aliabdoulayehaggar@usmba.ac.ma'],
            ['nom' => 'ENNAFAA', 'prenom' => 'fatima', 'email' => 'fatimaennafaa@gmail.com'],
            ['nom' => 'bouchama', 'prenom' => 'adnane', 'email' => 'adnane963@gmail.com'],
            ['nom' => 'bahlas', 'prenom' => 'rababe', 'email' => 'rababebahlas@gmail.com'],
            ['nom' => 'BENALIA', 'prenom' => 'Saïd', 'email' => 'doc.benalia1@gmail.com'],
            ['nom' => 'Benmrid', 'prenom' => 'Bouchra', 'email' => 'bouchra.benmrid@outlook.com'],
            ['nom' => 'hammouti', 'prenom' => 'yousra', 'email' => 'hammouti.yousra@ump.ac.ma'],
            ['nom' => 'Bouziane', 'prenom' => 'Salma', 'email' => 'bouzianesalma@iav.ac.ma'],
            ['nom' => 'GAADI', 'prenom' => 'Amina', 'email' => 'aminagaadi29@gmail.com'],
            ['nom' => 'Idrissi', 'prenom' => 'Houda', 'email' => 'h.idrissi@iav.ac.ma'],
            ['nom' => 'slimi', 'prenom' => 'fathia', 'email' => 'slimifathia@gmail.com'],
            ['nom' => 'Bkiri', 'prenom' => 'Dounia', 'email' => 'd.bkiri@iav.ac.ma'],
            ['nom' => 'Flouchi', 'prenom' => 'Maroine', 'email' => 'maroine_flouchi@um5.ac.ma'],
            ['nom' => 'Milouk', 'prenom' => 'Fatimazahra', 'email' => 'f.milouk@ispitsfes.ac.ma'],
            ['nom' => 'Kallala', 'prenom' => 'Rim', 'email' => 'rim.kallala@fmdm.u-monastir.tn'],
            ['nom' => 'Ben Ajiba', 'prenom' => 'Yousra', 'email' => 'yousra.benajiba1@etu.uae.ac.ma'],
            ['nom' => 'ESSAID', 'prenom' => 'MOUATASSIM BILLAH', 'email' => 'essaid053@gmail.com'],
            ['nom' => 'LAKHLIFI', 'prenom' => 'Tarik', 'email' => 't.lakhlifi@edu.umi.ac.ma'],
            ['nom' => 'DIOUCHI', 'prenom' => 'Jihad', 'email' => 'jihad.diouchi@uir.ac.ma'],
            ['nom' => 'Sekkout', 'prenom' => 'Zineb', 'email' => 'zineb.sekkout-etu@etu.univh2c.ma'],
            ['nom' => 'EL AFAKI FELLAH', 'prenom' => 'WAJIHA', 'email' => 'wajiha.elafakifellah@etu.uae.ac.ma'],
            ['nom' => 'ZRIRATE', 'prenom' => 'OMAIMA', 'email' => 'zromaima@gmail.com'],
            ['nom' => 'AZEKOUR', 'prenom' => 'ASMA', 'email' => 'asma.azekour-etu@etu.univh2c.ma'],
            ['nom' => 'BOUDAIA', 'prenom' => 'Omaima', 'email' => 'omaima.boudaia@gmail.com'],
            ['nom' => 'AIT RAMI', 'prenom' => 'OUMAIMA', 'email' => 'oumaima.aitrami.13@gmail.com'],
            ['nom' => 'BOUANAN', 'prenom' => 'Salma', 'email' => 'salmabouanan2020@gmail.com'],
            ['nom' => 'Laala', 'prenom' => 'Manal', 'email' => 'manallaala74@gmail.com'],
            ['nom' => 'SILLAHI', 'prenom' => 'BOUCHRA', 'email' => 'bouchra.sillahi@gmail.com'],
            ['nom' => 'LAOUIJA', 'prenom' => 'ZAHRAA', 'email' => 'zahraalaouija13@gmail.com'],
            ['nom' => 'El Mouns', 'prenom' => 'Badr-ddine', 'email' => 'elmouns.badr@gmail.com'],
            ['nom' => 'ADJE', 'prenom' => 'Ogbonnikan Franck', 'email' => 'franck.adje@ucoopia.org'],
            ['nom' => 'BEHLAOUANE', 'prenom' => 'Soukaina', 'email' => 'soukainabehlaouane7@gmail.com'],
            ['nom' => 'EL FENNI', 'prenom' => 'NOUHAILA', 'email' => 'nouhaelfenni@gmail.com'],
            ['nom' => 'OUHEMMOU', 'prenom' => 'ZINEB', 'email' => 'ouhemmouzineb@gmail.com'],
            ['nom' => 'EL HAMDAOUI', 'prenom' => 'CHAIMA', 'email' => 'elhamdaouichaima002@gmail.com'],
            ['nom' => 'MOUSSI', 'prenom' => 'OUTHMAN', 'email' => 'outhmanmoussi127@gmail.com'],
            ['nom' => 'KHOUDIRI', 'prenom' => 'IBTISSAM', 'email' => 'ibtissam.khoudiri-etu@etu.univh2c.ma'],
            ['nom' => 'BOUANNOUNOU', 'prenom' => 'Fatima', 'email' => 'fatima.bouannounou@gmail.com'],
            ['nom' => 'OUMA', 'prenom' => 'Younes', 'email' => 'oumayounes@iav.ac.ma'],
            ['nom' => 'NSENGIYU;VA', 'prenom' => 'Nestor', 'email' => 'nsenginesto2@gmail.com'],
            ['nom' => 'el karrouti', 'prenom' => 'oumaima', 'email' => 'oumaima.elkarouti001@gmail.com'],
            ['nom' => 'Lamaizi', 'prenom' => 'Assya', 'email' => 'assya.lamaizi@gmail.com'],
            ['nom' => 'Chelh', 'prenom' => 'Aya', 'email' => 'aya.chelh@um5r.ac.ma'],
            ['nom' => 'EL-BACHA', 'prenom' => 'Rachid', 'email' => 'rachid.elbacha@usms.ac.ma'],
            ['nom' => 'YAACOUBI', 'prenom' => 'KHADIJA', 'email' => 'k.yaacoubi@gmail.com'],
            ['nom' => 'KEBE', 'prenom' => 'Ousseynou', 'email' => 'kebeousseynou17@yahoo.fr'],
            ['nom' => 'ABAIDA', 'prenom' => 'BARAE', 'email' => 'barae.abaida@gmail.com'],
            ['nom' => 'Oumayma', 'prenom' => 'Sayah', 'email' => 'oumaymasayah0@gmail.com'],
            ['nom' => 'ADEL', 'prenom' => 'Maha', 'email' => 'Maha.adeel99@gmail.com'],
            ['nom' => 'EL HAMMIOUI', 'prenom' => 'YOUSSEF', 'email' => 'youssef.elhammioui@usms.ma'],
            ['nom' => 'FAGRACHE', 'prenom' => 'Ilham', 'email' => 'ilhamfagrach96@gmail.com'],
            ['nom' => 'Khald', 'prenom' => 'Hajar', 'email' => 'khaldhajar01@gmail.com'],
            ['nom' => 'Nouissi', 'prenom' => 'Atika', 'email' => 'nouissiatika@gmail.com'],
            ['nom' => 'CHIBOUB', 'prenom' => 'Basma', 'email' => 'basmachiboub@gmail.com'],
            ['nom' => 'EL MANSOURI', 'prenom' => 'Ibtissam', 'email' => 'elmansouriibtissam397@gmail.com'],
            ['nom' => 'KADDOURI', 'prenom' => 'YAMNA', 'email' => 'yamina.kadd.yk@gmail.com'],
            ['nom' => 'El fayq', 'prenom' => 'Soukaina', 'email' => 'elfayq.soukaina@gmail.com'],
            ['nom' => 'Adnane', 'prenom' => 'Fadya', 'email' => 'adnanefadya@gmail.com'],
            ['nom' => 'ABI', 'prenom' => 'Oussama', 'email' => 'Oabi@um6ss.ma'],
            ['nom' => 'OUSSI', 'prenom' => 'MOHAMED', 'email' => 'mo.oussi@edu.umi.ac.ma'],
            ['nom' => 'Wanaim', 'prenom' => 'Essaadia', 'email' => 'essaadia.wanaim-etu@etu.univh2c.ma'],
            ['nom' => 'NADI', 'prenom' => 'HAMID', 'email' => 'nadihamid01@gmail.com'],
            ['nom' => 'RABAH', 'prenom' => 'Najwa', 'email' => 'najwarabah99@gmail.com'],
            ['nom' => 'CHRAYAH', 'prenom' => 'Saloua', 'email' => 'saloua.chrayah@usmba.ac.ma'],
            ['nom' => 'ABID', 'prenom' => 'Fatima zahra', 'email' => 'fatimazahra.abid@ump.ac.ma'],
            ['nom' => 'ABBASSI', 'prenom' => 'Milouda', 'email' => 'milouda.abbassi@ump.ac.ma'],
            ['nom' => 'Nafai', 'prenom' => 'Manal', 'email' => 'nafaimanal@gmail.com'],
            ['nom' => 'Afassi', 'prenom' => 'Fatima', 'email' => 'fatima.afassi@etu.uae.ac.ma'],
            ['nom' => 'EL BAHAT', 'prenom' => 'ZAKARIA', 'email' => 'zakaria.elbahat@etu.uae.ac.ma'],
            ['nom' => 'DAIHI', 'prenom' => 'DADAIE', 'email' => 'dadaie.daihi@um6p.ma'],
            ['nom' => 'Melaylou', 'prenom' => 'Fedwa', 'email' => 'fedwamelaylou2000@gmail.com'],
            ['nom' => 'DRIOUACH', 'prenom' => 'Yamina', 'email' => 'yamina.driouach86@gmail.com'],
            ['nom' => 'ouakourou', 'prenom' => 'hajar', 'email' => 'hajar.ouakourou@etu.uae.ac.ma'],
            ['nom' => 'AOUAD', 'prenom' => 'Otmane', 'email' => 'otmanfmptlabo@gmail.com'],
            ['nom' => 'zouaoui', 'prenom' => 'zakia', 'email' => 'zakia.zouaoui@etu.uae.ac.ma'],
            ['nom' => 'EL ASRI', 'prenom' => 'Sara', 'email' => 'sara.elasri@etu.uae.ac.ma'],
            ['nom' => 'NOURI', 'prenom' => 'CHAIMAE', 'email' => 'nourichaimae6@gmail.com'],
            ['nom' => 'EL MONTACER', 'prenom' => 'Kaoutar', 'email' => 'kaoutar110@outlook.fr'],
            ['nom' => 'ASLI', 'prenom' => 'Halima', 'email' => 'asli.halima031@gmail.com'],
            ['nom' => 'SABRI', 'prenom' => 'Mariam', 'email' => 'mariam.sabri04@gmail.com'],
            ['nom' => 'CHOUACHA', 'prenom' => 'WISSAL', 'email' => 'chouachawissal@gmail.com'],
            ['nom' => 'metni', 'prenom' => 'khairo el baria', 'email' => 'metnikhairoelbaria@gmail.com'],
            ['nom' => 'SAFA', 'prenom' => 'Fatima', 'email' => 'fatima.safa200@gmail.com'],
            ['nom' => 'chattat', 'prenom' => 'Khaoula', 'email' => 'chattat.khaoula@ucd.ac.ma'],
            ['nom' => 'Benabdelkamel', 'prenom' => 'Safaa', 'email' => 'safaa.benabdelkamel@um5r.ac.ma'],
            ['nom' => 'Chaib', 'prenom' => 'Nouhaila', 'email' => 'nouhailachaib5@gmail.com'],
            ['nom' => 'Chamnaoui', 'prenom' => 'Salma', 'email' => 'chamnaouisalma@gmail.com'],
            ['nom' => 'BENCHEIKH', 'prenom' => 'Abdellah', 'email' => 'abdellah.bencheikh@um5r.ac.ma'],
            ['nom' => 'El Bahdaoui', 'prenom' => 'Safaa', 'email' => 'safaa.elbahdaoui@etu.uae.ac.ma'],
            ['nom' => 'Ennaciri', 'prenom' => 'Ghita', 'email' => 'ghita.ennaciri@etu.uae.ac.ma'],
            ['nom' => 'Zidouemba', 'prenom' => 'Boukaré', 'email' => 'boukarez48@gmail.com'],
            ['nom' => 'QASMI', 'prenom' => 'Wissal', 'email' => 'wissal.qasmi@iav.ac.ma'],
            ['nom' => 'AIT HA', 'prenom' => 'Oumayma', 'email' => 'aithaoumeime@gmail.com'],
            ['nom' => 'Mellal', 'prenom' => 'Ayoub', 'email' => 'ayoub.mellal2@gmail.com'],
            ['nom' => 'BENNAR', 'prenom' => 'Mohamed', 'email' => 'bennarmohamed123@gmail.com'],
            ['nom' => 'Abbas', 'prenom' => 'Sahar', 'email' => 'saharabbas.sahar@gmail.com'],
            ['nom' => 'El Herch', 'prenom' => 'Chaimae', 'email' => 'Ch.elherch@gmail.com'],
            ['nom' => 'FAZG', 'prenom' => 'Yassamine', 'email' => 'yassaminefazg98@gmail.com'],
            ['nom' => 'EL FADILI', 'prenom' => 'Nour El Houda', 'email' => 'nourelhouda.elfadili@etu.uae.ac.ma'],
            ['nom' => 'RAOELINA', 'prenom' => 'Ionick Eugenio', 'email' => 'ieraoelina@gmail.com'],
            ['nom' => 'SAISSI', 'prenom' => 'SAHAR', 'email' => 'saissisahar@iav.ac.ma'],
            ['nom' => 'Bourquia', 'prenom' => 'Maria', 'email' => 'm.bourquia@iav.ac.ma'],
            ['nom' => 'Zahri', 'prenom' => 'Abderrahmane', 'email' => 'zahriabderrahmane@iav.ac.ma'],
            ['nom' => 'el moukken', 'prenom' => 'sanae', 'email' => 'sanae.moukken@gmail.com'],
            ['nom' => 'EL YOUSFI', 'prenom' => 'HAJAR', 'email' => 'elyousfi.hajar04@gmail.com'],
            ['nom' => 'Mesbah', 'prenom' => 'Naima', 'email' => 'naimamesbah99@gmail.com'],
            ['nom' => 'QOSTAL', 'prenom' => 'Mariem', 'email' => 'mariemqostal.20@gmail.com'],
            ['nom' => 'ADOUD', 'prenom' => 'IMANE', 'email' => 'iadoud@um6ss.ma'],
            ['nom' => 'AMZIL', 'prenom' => 'Mohamed', 'email' => 'amzilmohamed12@gmail.com'],
            ['nom' => 'zamour', 'prenom' => 'ibtissam', 'email' => 'ibtissam.zamour@etu.uae.ac.ma'],
            ['nom' => 'El Mahi', 'prenom' => 'Kaoutar', 'email' => 'ka.elmahi.99@gmail.com'],
            ['nom' => 'Atertor', 'prenom' => 'Oumaima', 'email' => 'o.atertor@iav.ac.ma'],
            ['nom' => 'ABRAOU', 'prenom' => 'Hajiba', 'email' => 'hajiba.atl.2023@gmail.com'],
            ['nom' => 'Fanjaoui', 'prenom' => 'Nada', 'email' => 'naada.fan@hotmail.com'],
            ['nom' => 'Kirat', 'prenom' => 'Meryeme', 'email' => 'meryeme.kirate@usmba.ac.ma'],
            ['nom' => 'LARAQUI HOUSSAINI', 'prenom' => 'SORAYA', 'email' => 'Soraya.laraqui@usmba.ac.ma'],
            ['nom' => 'mabrouki', 'prenom' => 'Selma', 'email' => 'mabrouki.selma@ucd.ac.ma'],
            ['nom' => 'YASSINE', 'prenom' => 'Brahim', 'email' => 'yassine91brahim@gmail.com'],
            ['nom' => 'choukri', 'prenom' => 'imane', 'email' => 'i.choukri@iav.ac.ma'],
            ['nom' => 'EL FAZIKI', 'prenom' => 'Imane', 'email' => 'imane.elfaziki@usmba.ac.ma'],
            ['nom' => 'Lahsaini', 'prenom' => 'Fatima Zahraa', 'email' => 'f.lahsaini@iav.ac.ma'],
            ['nom' => 'BEN MAHJOUB', 'prenom' => 'Manal', 'email' => 'ben.mahjoub.manal@gmail.com'],
            ['nom' => 'RADI', 'prenom' => 'RADIANOIR', 'email' => 'radianoir022@gmail.com'],
            ['nom' => 'el karrouti', 'prenom' => 'oumaima', 'email' => 'oumaima_elkarrouti@um5.ac.ma'],
            ['nom' => 'ELJOUHARI', 'prenom' => 'Zineb', 'email' => 'zinebeljouhari.iav@gmail.com'],
            ['nom' => 'AL MALKI', 'prenom' => 'Chaimaa', 'email' => 'calmalki@um6ss.ma'],
            ['nom' => 'LAAKILI', 'prenom' => 'AMAL', 'email' => 'amallmbm@gmail.com'],
            ['nom' => 'Ouarzazi', 'prenom' => 'Laila', 'email' => 'lailaouarzazi@gmail.com'],
            ['nom' => 'MAGOURI', 'prenom' => 'Manar', 'email' => 'manar.mag001@gmail.com'],
        ];

        // Deduplicate by email (keep last occurrence)
        $unique = [];
        foreach ($data as $row) {
            $unique[strtolower(trim($row['email']))] = $row;
        }

        $inserted = 0;
        $updated  = 0;

        foreach ($unique as $email => $row) {
            $name = trim($row['prenom'] . ' ' . $row['nom']);
            $existing = Participant::where('email', $email)->first();
            if ($existing) {
                $existing->update(['name' => $name]);
                $updated++;
            } else {
                Participant::create(['email' => $email, 'name' => $name]);
                $inserted++;
            }
        }

        $total = Participant::count();
        echo "Insérés: $inserted | Mis à jour: $updated | Total en base: $total\n";
    }
}
